import Head from 'next/head'
import React from 'react'

export default function Header() {
    return (
        <Head>
            <title>TRANSPORTENETA</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/argentina_flag.png" />
        </Head>
    )
}
